{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPEGKzBFklgekhf2MmUacnK",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rajansingh387/assignments/blob/main/Exception_Handling_Assignment_2.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
        "Note: Here Exception class refers to the base class for all the exceptions."
      ],
      "metadata": {
        "id": "2YynJlZ2lq4Z"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "custom exceptions allow you to define your own types of errors that are not there in the exceptions list. it is a good practice to derive custom exceptions from the base exception class.\n",
        "\n",
        "by using the exception class as a base for your custom exception, you're making sure that everyone who will read your code in the future will understands what you are trying to create and how to handle it properly. it is like using same grammer technique while writing a new line. this helps in better organization, readability, and maintainability of your code.\n",
        "\n",
        "by using the Exception class as the base for your custom exception, you are ensuring that your new problem is part of the same family as all the other problems that the programming language can handle. This makes it easier for your program to understand and manage your custom exception.\n",
        "it helps in maintaing consistency, compatibility, and clarity, making it easier for your program to tackle both common and unique problems.\n",
        "\n"
      ],
      "metadata": {
        "id": "ovCRxX17mDLx"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q2. Write a python program to print Python Exception Hierarchy."
      ],
      "metadata": {
        "id": "08OcT1-Ip5Rx"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"this python program takes an exception class as an input and will print the class and its subclass,\n",
        "this will start with base class and it will print main class and its sub class, also i used indent to seprate\n",
        "main class and subclass and also to display hierarchy\"\"\""
      ],
      "metadata": {
        "id": "PkP5F3whp7ZS"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "Ry_z3_ps460b",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "08fd5a37-990b-495f-f6e7-15bcc1c2c0aa"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "<class 'BaseException'>\n",
            "    <class 'Exception'>\n",
            "        <class 'TypeError'>\n",
            "            <class 'email.errors.MultipartConversionError'>\n",
            "            <class 'decimal.FloatOperation'>\n",
            "            <class 'numpy.core._exceptions.UFuncTypeError'>\n",
            "                <class 'numpy.core._exceptions._UFuncBinaryResolutionError'>\n",
            "                <class 'numpy.core._exceptions._UFuncNoLoopError'>\n",
            "                <class 'numpy.core._exceptions._UFuncCastingError'>\n",
            "                    <class 'numpy.core._exceptions._UFuncInputCastingError'>\n",
            "                    <class 'numpy.core._exceptions._UFuncOutputCastingError'>\n",
            "            <class 'matplotlib.units.ConversionError'>\n",
            "            <class 'pyarrow.lib.ArrowTypeError'>\n",
            "            <class 'requests.exceptions.StreamConsumedError'>\n",
            "            <class 'google.auth.exceptions.InvalidType'>\n",
            "            <class 'pandas._libs.tslibs.offsets.ApplyTypeError'>\n",
            "            <class 'tqdm.std.TqdmTypeError'>\n",
            "        <class 'StopAsyncIteration'>\n",
            "        <class 'StopIteration'>\n",
            "        <class 'ImportError'>\n",
            "            <class 'ModuleNotFoundError'>\n",
            "                <class 'importlib.metadata.PackageNotFoundError'>\n",
            "            <class 'zipimport.ZipImportError'>\n",
            "        <class 'OSError'>\n",
            "            <class 'ConnectionError'>\n",
            "                <class 'BrokenPipeError'>\n",
            "                <class 'ConnectionAbortedError'>\n",
            "                <class 'ConnectionRefusedError'>\n",
            "                <class 'ConnectionResetError'>\n",
            "                    <class 'http.client.RemoteDisconnected'>\n",
            "            <class 'BlockingIOError'>\n",
            "            <class 'ChildProcessError'>\n",
            "            <class 'FileExistsError'>\n",
            "            <class 'FileNotFoundError'>\n",
            "                <class 'matplotlib.ExecutableNotFoundError'>\n",
            "            <class 'IsADirectoryError'>\n",
            "            <class 'NotADirectoryError'>\n",
            "            <class 'InterruptedError'>\n",
            "                <class 'zmq.error.InterruptedSystemCall'>\n",
            "            <class 'PermissionError'>\n",
            "            <class 'ProcessLookupError'>\n",
            "            <class 'TimeoutError'>\n",
            "            <class 'io.UnsupportedOperation'>\n",
            "            <class 'signal.itimer_error'>\n",
            "            <class 'shutil.Error'>\n",
            "                <class 'shutil.SameFileError'>\n",
            "            <class 'shutil.SpecialFileError'>\n",
            "            <class 'shutil.ExecError'>\n",
            "            <class 'shutil.ReadError'>\n",
            "            <class 'socket.herror'>\n",
            "            <class 'socket.gaierror'>\n",
            "            <class 'ssl.SSLError'>\n",
            "                <class 'ssl.SSLCertVerificationError'>\n",
            "                <class 'ssl.SSLZeroReturnError'>\n",
            "                <class 'ssl.SSLWantWriteError'>\n",
            "                <class 'ssl.SSLWantReadError'>\n",
            "                <class 'ssl.SSLSyscallError'>\n",
            "                <class 'ssl.SSLEOFError'>\n",
            "            <class 'urllib.error.URLError'>\n",
            "                <class 'urllib.error.HTTPError'>\n",
            "                <class 'urllib.error.ContentTooShortError'>\n",
            "            <class 'gzip.BadGzipFile'>\n",
            "            <class 'socks.ProxyError'>\n",
            "                <class 'socks.GeneralProxyError'>\n",
            "                <class 'socks.ProxyConnectionError'>\n",
            "                <class 'socks.SOCKS5AuthError'>\n",
            "                <class 'socks.SOCKS5Error'>\n",
            "                <class 'socks.SOCKS4Error'>\n",
            "                <class 'socks.HTTPError'>\n",
            "            <class 'PIL.UnidentifiedImageError'>\n",
            "            <class 'http.cookiejar.LoadError'>\n",
            "            <class 'requests.exceptions.RequestException'>\n",
            "                <class 'requests.exceptions.InvalidJSONError'>\n",
            "                    <class 'requests.exceptions.JSONDecodeError'>\n",
            "                <class 'requests.exceptions.HTTPError'>\n",
            "                <class 'requests.exceptions.ConnectionError'>\n",
            "                    <class 'requests.exceptions.ProxyError'>\n",
            "                    <class 'requests.exceptions.SSLError'>\n",
            "                    <class 'requests.exceptions.ConnectTimeout'>\n",
            "                <class 'requests.exceptions.Timeout'>\n",
            "                    <class 'requests.exceptions.ConnectTimeout'>\n",
            "                    <class 'requests.exceptions.ReadTimeout'>\n",
            "                <class 'requests.exceptions.URLRequired'>\n",
            "                <class 'requests.exceptions.TooManyRedirects'>\n",
            "                <class 'requests.exceptions.MissingSchema'>\n",
            "                <class 'requests.exceptions.InvalidSchema'>\n",
            "                <class 'requests.exceptions.InvalidURL'>\n",
            "                    <class 'requests.exceptions.InvalidProxyURL'>\n",
            "                <class 'requests.exceptions.InvalidHeader'>\n",
            "                <class 'requests.exceptions.ChunkedEncodingError'>\n",
            "                <class 'requests.exceptions.ContentDecodingError'>\n",
            "                <class 'requests.exceptions.StreamConsumedError'>\n",
            "                <class 'requests.exceptions.RetryError'>\n",
            "                <class 'requests.exceptions.UnrewindableBodyError'>\n",
            "            <class 'google.auth.exceptions.OSError'>\n",
            "            <class 'pandas.errors.DatabaseError'>\n",
            "        <class 'EOFError'>\n",
            "            <class 'asyncio.exceptions.IncompleteReadError'>\n",
            "        <class 'RuntimeError'>\n",
            "            <class 'RecursionError'>\n",
            "            <class 'NotImplementedError'>\n",
            "                <class 'IPython.core.error.StdinNotImplementedError'>\n",
            "                <class 'zmq.error.ZMQVersionError'>\n",
            "                <class 'pyarrow.lib.ArrowNotImplementedError'>\n",
            "                <class 'pandas.errors.AbstractMethodError'>\n",
            "            <class '_frozen_importlib._DeadlockError'>\n",
            "            <class 'threading.BrokenBarrierError'>\n",
            "            <class 'concurrent.futures._base.BrokenExecutor'>\n",
            "                <class 'concurrent.futures.thread.BrokenThreadPool'>\n",
            "            <class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
            "            <class 'setuptools.errors.RemovedCommandError'>\n",
            "            <class 'setuptools.errors.PackageDiscoveryError'>\n",
            "            <class 'numpy.TooHardError'>\n",
            "            <class 'pkg_resources.ExtractionError'>\n",
            "            <class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
            "            <class 'requests.cookies.CookieConflictError'>\n",
            "            <class 'pandas.errors.PyperclipException'>\n",
            "                <class 'pandas.errors.PyperclipWindowsException'>\n",
            "            <class 'pyproj.exceptions.ProjError'>\n",
            "                <class 'pyproj.exceptions.CRSError'>\n",
            "            <class 'pyproj.exceptions.GeodError'>\n",
            "            <class 'pyproj.exceptions.DataDirError'>\n",
            "        <class 'NameError'>\n",
            "            <class 'UnboundLocalError'>\n",
            "            <class 'pandas.errors.NumExprClobberingError'>\n",
            "            <class 'pandas.errors.UndefinedVariableError'>\n",
            "        <class 'AttributeError'>\n",
            "            <class 'dataclasses.FrozenInstanceError'>\n",
            "            <class 'pandas._config.config.OptionError'>\n",
            "        <class 'SyntaxError'>\n",
            "            <class 'IndentationError'>\n",
            "                <class 'TabError'>\n",
            "            <class 'xml.etree.ElementTree.ParseError'>\n",
            "        <class 'LookupError'>\n",
            "            <class 'IndexError'>\n",
            "                <class 'numpy.AxisError'>\n",
            "                <class 'matplotlib.streamplot.OutOfBounds'>\n",
            "                <class 'pyarrow.lib.ArrowIndexError'>\n",
            "            <class 'KeyError'>\n",
            "                <class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
            "                <class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
            "                <class 'pyarrow.lib.ArrowKeyError'>\n",
            "                <class 'pytz.exceptions.UnknownTimeZoneError'>\n",
            "                <class 'zoneinfo._common.ZoneInfoNotFoundError'>\n",
            "                <class 'pandas._config.config.OptionError'>\n",
            "                <class 'pandas.errors.UnsortedIndexError'>\n",
            "                <class 'tqdm.std.TqdmKeyError'>\n",
            "            <class 'encodings.CodecRegistryError'>\n",
            "        <class 'ValueError'>\n",
            "            <class 'UnicodeError'>\n",
            "                <class 'UnicodeEncodeError'>\n",
            "                <class 'UnicodeDecodeError'>\n",
            "                <class 'UnicodeTranslateError'>\n",
            "                <class 'idna.core.IDNAError'>\n",
            "                    <class 'idna.core.IDNABidiError'>\n",
            "                    <class 'idna.core.InvalidCodepoint'>\n",
            "                    <class 'idna.core.InvalidCodepointContext'>\n",
            "            <class 'io.UnsupportedOperation'>\n",
            "            <class 'json.decoder.JSONDecodeError'>\n",
            "                <class 'requests.exceptions.JSONDecodeError'>\n",
            "            <class '_hashlib.UnsupportedDigestmodError'>\n",
            "            <class 'binascii.Error'>\n",
            "            <class 'pygments.util.ClassNotFound'>\n",
            "            <class 'ssl.SSLCertVerificationError'>\n",
            "            <class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
            "            <class 'email.errors.MessageDefect'>\n",
            "                <class 'email.errors.NoBoundaryInMultipartDefect'>\n",
            "                <class 'email.errors.StartBoundaryNotFoundDefect'>\n",
            "                <class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
            "                <class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
            "                <class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
            "                <class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
            "                <class 'email.errors.MultipartInvariantViolationDefect'>\n",
            "                <class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
            "                <class 'email.errors.UndecodableBytesDefect'>\n",
            "                <class 'email.errors.InvalidBase64PaddingDefect'>\n",
            "                <class 'email.errors.InvalidBase64CharactersDefect'>\n",
            "                <class 'email.errors.InvalidBase64LengthDefect'>\n",
            "                <class 'email.errors.HeaderDefect'>\n",
            "                    <class 'email.errors.InvalidHeaderDefect'>\n",
            "                    <class 'email.errors.HeaderMissingRequiredValue'>\n",
            "                    <class 'email.errors.NonPrintableDefect'>\n",
            "                    <class 'email.errors.ObsoleteHeaderDefect'>\n",
            "                    <class 'email.errors.NonASCIILocalPartDefect'>\n",
            "                    <class 'email.errors.InvalidDateDefect'>\n",
            "            <class 'calendar.IllegalMonthError'>\n",
            "            <class 'calendar.IllegalWeekdayError'>\n",
            "            <class 'IPython.core.magics.code.MacroToEdit'>\n",
            "            <class 'dateutil.parser._parser.ParserError'>\n",
            "            <class 'setuptools._vendor.more_itertools.more.UnequalIterablesError'>\n",
            "            <class 'setuptools._vendor.packaging._elffile.ELFInvalid'>\n",
            "            <class 'setuptools.extern.packaging.version.InvalidVersion'>\n",
            "            <class 'setuptools.extern.packaging.utils.InvalidWheelFilename'>\n",
            "            <class 'setuptools.extern.packaging.utils.InvalidSdistFilename'>\n",
            "            <class 'setuptools.extern.packaging.specifiers.InvalidSpecifier'>\n",
            "            <class 'setuptools.extern.packaging.markers.InvalidMarker'>\n",
            "            <class 'setuptools.extern.packaging.markers.UndefinedComparison'>\n",
            "            <class 'setuptools.extern.packaging.markers.UndefinedEnvironmentName'>\n",
            "            <class 'setuptools.extern.packaging.requirements.InvalidRequirement'>\n",
            "            <class 'google.colab._import_hooks._cv2.DisabledFunctionError'>\n",
            "            <class 'numpy.compat._pep440.InvalidVersion'>\n",
            "            <class 'numpy.AxisError'>\n",
            "            <class 'packaging.version.InvalidVersion'>\n",
            "            <class 'defusedxml.common.DefusedXmlException'>\n",
            "                <class 'defusedxml.common.DTDForbidden'>\n",
            "                <class 'defusedxml.common.EntitiesForbidden'>\n",
            "                <class 'defusedxml.common.ExternalReferenceForbidden'>\n",
            "                <class 'defusedxml.common.NotSupportedError'>\n",
            "            <class 'matplotlib.bezier.NonIntersectingPathException'>\n",
            "            <class 'plistlib.InvalidFileException'>\n",
            "            <class 'pkg_resources._vendor.more_itertools.recipes.UnequalIterablesError'>\n",
            "            <class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
            "            <class 'pkg_resources._vendor.packaging._elffile.ELFInvalid'>\n",
            "            <class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
            "            <class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
            "            <class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
            "            <class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
            "            <class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
            "            <class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
            "            <class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
            "                <class 'pkg_resources.RequirementParseError'>\n",
            "            <class 'pyarrow.lib.ArrowInvalid'>\n",
            "            <class 'urllib3.exceptions.LocationValueError'>\n",
            "                <class 'urllib3.exceptions.LocationParseError'>\n",
            "                <class 'urllib3.exceptions.URLSchemeUnknown'>\n",
            "                    <class 'urllib3.exceptions.ProxySchemeUnknown'>\n",
            "            <class 'urllib3.exceptions.ResponseNotChunked'>\n",
            "            <class 'urllib3.exceptions.ProxySchemeUnsupported'>\n",
            "            <class 'ipaddress.AddressValueError'>\n",
            "            <class 'ipaddress.NetmaskValueError'>\n",
            "            <class 'urllib3.util.ssl_match_hostname.CertificateError'>\n",
            "            <class 'requests.exceptions.MissingSchema'>\n",
            "            <class 'requests.exceptions.InvalidSchema'>\n",
            "            <class 'requests.exceptions.InvalidURL'>\n",
            "                <class 'requests.exceptions.InvalidProxyURL'>\n",
            "            <class 'requests.exceptions.InvalidHeader'>\n",
            "            <class 'google.auth.exceptions.MalformedError'>\n",
            "            <class 'google.auth.exceptions.InvalidResource'>\n",
            "            <class 'google.auth.exceptions.InvalidOperation'>\n",
            "            <class 'google.auth.exceptions.InvalidValue'>\n",
            "            <class 'pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime'>\n",
            "            <class 'pandas._libs.tslibs.np_datetime.OutOfBoundsTimedelta'>\n",
            "            <class 'pandas.util.version.InvalidVersion'>\n",
            "            <class 'pandas._libs.tslibs.parsing.DateParseError'>\n",
            "            <class 'pandas._libs.tslibs.period.IncompatibleFrequency'>\n",
            "            <class 'pandas.errors.IntCastingNaNError'>\n",
            "            <class 'pandas.errors.NullFrequencyError'>\n",
            "            <class 'pandas.errors.UnsupportedFunctionCall'>\n",
            "            <class 'pandas.errors.ParserError'>\n",
            "            <class 'pandas.errors.EmptyDataError'>\n",
            "            <class 'pandas.errors.MergeError'>\n",
            "            <class 'pandas.errors.DuplicateLabelError'>\n",
            "            <class 'pandas.errors.SettingWithCopyError'>\n",
            "            <class 'statistics.StatisticsError'>\n",
            "        <class 'AssertionError'>\n",
            "            <class 'urllib3.exceptions.ProxySchemeUnknown'>\n",
            "        <class 'ArithmeticError'>\n",
            "            <class 'FloatingPointError'>\n",
            "            <class 'OverflowError'>\n",
            "            <class 'ZeroDivisionError'>\n",
            "                <class 'decimal.DivisionByZero'>\n",
            "                <class 'decimal.DivisionUndefined'>\n",
            "            <class 'decimal.DecimalException'>\n",
            "                <class 'decimal.Clamped'>\n",
            "                <class 'decimal.Rounded'>\n",
            "                    <class 'decimal.Underflow'>\n",
            "                    <class 'decimal.Overflow'>\n",
            "                <class 'decimal.Inexact'>\n",
            "                    <class 'decimal.Underflow'>\n",
            "                    <class 'decimal.Overflow'>\n",
            "                <class 'decimal.Subnormal'>\n",
            "                    <class 'decimal.Underflow'>\n",
            "                <class 'decimal.DivisionByZero'>\n",
            "                <class 'decimal.FloatOperation'>\n",
            "                <class 'decimal.InvalidOperation'>\n",
            "                    <class 'decimal.ConversionSyntax'>\n",
            "                    <class 'decimal.DivisionImpossible'>\n",
            "                    <class 'decimal.DivisionUndefined'>\n",
            "                    <class 'decimal.InvalidContext'>\n",
            "        <class 'SystemError'>\n",
            "            <class 'encodings.CodecRegistryError'>\n",
            "        <class 'ReferenceError'>\n",
            "        <class 'MemoryError'>\n",
            "            <class 'numpy.core._exceptions._ArrayMemoryError'>\n",
            "            <class 'pyarrow.lib.ArrowMemoryError'>\n",
            "        <class 'BufferError'>\n",
            "        <class 'Warning'>\n",
            "            <class 'UserWarning'>\n",
            "                <class 'getpass.GetPassWarning'>\n",
            "                <class 'IPython.core.formatters.FormatterWarning'>\n",
            "                <class 'setuptools.warnings.SetuptoolsWarning'>\n",
            "                    <class 'setuptools.warnings.InformationOnly'>\n",
            "                    <class 'setuptools.warnings.SetuptoolsDeprecationWarning'>\n",
            "                        <class 'setuptools.config.setupcfg._AmbiguousMarker'>\n",
            "                        <class 'setuptools.config.setupcfg._DeprecatedConfig'>\n",
            "                        <class 'setuptools.config._apply_pyprojecttoml._WouldIgnoreField'>\n",
            "                        <class 'setuptools.dist.DistDeprecationWarning'>\n",
            "                    <class 'setuptools.config.pyprojecttoml._BetaConfiguration'>\n",
            "                    <class 'setuptools.config.pyprojecttoml._InvalidFile'>\n",
            "                <class 'numpy.VisibleDeprecationWarning'>\n",
            "                <class 'numpy.RankWarning'>\n",
            "                <class 'numpy.lib._iotools.ConversionWarning'>\n",
            "                <class 'numpy.polynomial.polyutils.RankWarning'>\n",
            "                <class 'cryptography.utils.CryptographyDeprecationWarning'>\n",
            "                <class 'pandas.errors.CSSWarning'>\n",
            "            <class 'EncodingWarning'>\n",
            "            <class 'DeprecationWarning'>\n",
            "                <class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
            "                <class 'numpy.ModuleDeprecationWarning'>\n",
            "                <class 'matplotlib._api.deprecation.MatplotlibDeprecationWarning'>\n",
            "                <class 'requests.exceptions.FileModeWarning'>\n",
            "                <class 'tqdm.std.TqdmDeprecationWarning'>\n",
            "            <class 'PendingDeprecationWarning'>\n",
            "            <class 'SyntaxWarning'>\n",
            "            <class 'RuntimeWarning'>\n",
            "                <class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
            "                <class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
            "                <class 'numpy.ComplexWarning'>\n",
            "                <class 'PIL.Image.DecompressionBombWarning'>\n",
            "                <class 'pkg_resources.PEP440Warning'>\n",
            "                <class 'zoneinfo._tzpath.InvalidTZPathWarning'>\n",
            "                <class 'tqdm._monitor.TqdmSynchronisationWarning'>\n",
            "                <class 'tqdm.std.TqdmMonitorWarning'>\n",
            "            <class 'FutureWarning'>\n",
            "                <class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
            "                <class 'numpy.ma.core.MaskedArrayFutureWarning'>\n",
            "                <class 'shapely.errors.ShapelyDeprecationWarning'>\n",
            "                <class 'tqdm.std.TqdmExperimentalWarning'>\n",
            "            <class 'ImportWarning'>\n",
            "            <class 'UnicodeWarning'>\n",
            "            <class 'BytesWarning'>\n",
            "            <class 'ResourceWarning'>\n",
            "            <class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
            "            <class 'matplotlib.mathtext.MathTextWarning'>\n",
            "            <class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
            "            <class 'urllib3.exceptions.HTTPWarning'>\n",
            "                <class 'urllib3.exceptions.SecurityWarning'>\n",
            "                    <class 'urllib3.exceptions.InsecureRequestWarning'>\n",
            "                    <class 'urllib3.exceptions.NotOpenSSLWarning'>\n",
            "                    <class 'urllib3.exceptions.SystemTimeWarning'>\n",
            "                    <class 'urllib3.exceptions.InsecurePlatformWarning'>\n",
            "                <class 'urllib3.exceptions.DependencyWarning'>\n",
            "            <class 'requests.exceptions.RequestsWarning'>\n",
            "                <class 'requests.exceptions.FileModeWarning'>\n",
            "                <class 'requests.exceptions.RequestsDependencyWarning'>\n",
            "            <class 'grpc.experimental.ExperimentalApiWarning'>\n",
            "            <class 'pandas.errors.PerformanceWarning'>\n",
            "            <class 'pandas.errors.DtypeWarning'>\n",
            "            <class 'pandas.errors.ParserWarning'>\n",
            "            <class 'pandas.errors.AccessorRegistrationWarning'>\n",
            "            <class 'pandas.errors.SettingWithCopyWarning'>\n",
            "            <class 'pandas.errors.IncompatibilityWarning'>\n",
            "            <class 'pandas.errors.AttributeConflictWarning'>\n",
            "            <class 'pandas.errors.PossiblePrecisionLoss'>\n",
            "            <class 'pandas.errors.ValueLabelTypeMismatch'>\n",
            "            <class 'pandas.errors.InvalidColumnName'>\n",
            "            <class 'pandas.errors.CategoricalConversionWarning'>\n",
            "            <class 'tqdm.std.TqdmWarning'>\n",
            "                <class 'tqdm.std.TqdmExperimentalWarning'>\n",
            "                <class 'tqdm.std.TqdmDeprecationWarning'>\n",
            "                <class 'tqdm.std.TqdmMonitorWarning'>\n",
            "        <class 'warnings._OptionError'>\n",
            "        <class 're.error'>\n",
            "        <class 'sre_parse.Verbose'>\n",
            "        <class 'locale.Error'>\n",
            "        <class 'runpy._Error'>\n",
            "        <class 'subprocess.SubprocessError'>\n",
            "            <class 'subprocess.CalledProcessError'>\n",
            "            <class 'subprocess.TimeoutExpired'>\n",
            "        <class 'copy.Error'>\n",
            "        <class 'tokenize.TokenError'>\n",
            "        <class 'tokenize.StopTokenizing'>\n",
            "        <class 'zlib.error'>\n",
            "        <class '_lzma.LZMAError'>\n",
            "        <class 'shutil.RegistryError'>\n",
            "        <class 'shutil._GiveupOnFastCopy'>\n",
            "        <class 'inspect.ClassFoundException'>\n",
            "        <class 'inspect.EndOfBlock'>\n",
            "        <class 'traitlets.traitlets.TraitError'>\n",
            "        <class 'socket._GiveupOnSendfile'>\n",
            "        <class 'struct.error'>\n",
            "        <class '_pickle.PickleError'>\n",
            "            <class '_pickle.PicklingError'>\n",
            "            <class '_pickle.UnpicklingError'>\n",
            "        <class 'pickle._Stop'>\n",
            "        <class '_queue.Empty'>\n",
            "        <class 'queue.Full'>\n",
            "        <class 'argparse.ArgumentError'>\n",
            "        <class 'argparse.ArgumentTypeError'>\n",
            "        <class 'traitlets.config.loader.ConfigError'>\n",
            "            <class 'traitlets.config.loader.ConfigLoaderError'>\n",
            "                <class 'traitlets.config.loader.ArgumentError'>\n",
            "            <class 'traitlets.config.loader.ConfigFileNotFound'>\n",
            "        <class 'traitlets.config.configurable.ConfigurableError'>\n",
            "            <class 'traitlets.config.configurable.MultipleInstanceError'>\n",
            "        <class 'traitlets.config.application.ApplicationError'>\n",
            "        <class 'pydoc.ErrorDuringImport'>\n",
            "        <class 'bdb.BdbQuit'>\n",
            "        <class 'pdb.Restart'>\n",
            "        <class 'pexpect.exceptions.ExceptionPexpect'>\n",
            "            <class 'pexpect.exceptions.EOF'>\n",
            "            <class 'pexpect.exceptions.TIMEOUT'>\n",
            "        <class 'termios.error'>\n",
            "        <class 'ptyprocess.util.PtyProcessError'>\n",
            "        <class 'IPython.utils.process.FindCmdError'>\n",
            "        <class 'IPython.utils.path.HomeDirError'>\n",
            "        <class 'IPython.core.profiledir.ProfileDirError'>\n",
            "        <class 'IPython.core.error.IPythonCoreError'>\n",
            "            <class 'IPython.core.error.TryNext'>\n",
            "            <class 'IPython.core.error.UsageError'>\n",
            "            <class 'IPython.core.error.StdinNotImplementedError'>\n",
            "        <class 'IPython.core.error.InputRejected'>\n",
            "        <class 'getopt.GetoptError'>\n",
            "        <class 'binascii.Incomplete'>\n",
            "        <class 'pygments.util.OptionError'>\n",
            "        <class 'pygments.filters.ErrorToken'>\n",
            "        <class 'IPython.core.prefilter.PrefilterError'>\n",
            "        <class 'IPython.core.alias.AliasError'>\n",
            "            <class 'IPython.core.alias.InvalidAliasError'>\n",
            "        <class 'sqlite3.Error'>\n",
            "            <class 'sqlite3.InterfaceError'>\n",
            "            <class 'sqlite3.DatabaseError'>\n",
            "                <class 'sqlite3.InternalError'>\n",
            "                <class 'sqlite3.OperationalError'>\n",
            "                <class 'sqlite3.ProgrammingError'>\n",
            "                <class 'sqlite3.IntegrityError'>\n",
            "                <class 'sqlite3.DataError'>\n",
            "                <class 'sqlite3.NotSupportedError'>\n",
            "        <class 'sqlite3.Warning'>\n",
            "        <class 'concurrent.futures._base.Error'>\n",
            "            <class 'concurrent.futures._base.CancelledError'>\n",
            "            <class 'concurrent.futures._base.TimeoutError'>\n",
            "            <class 'concurrent.futures._base.InvalidStateError'>\n",
            "        <class 'asyncio.exceptions.TimeoutError'>\n",
            "        <class 'asyncio.exceptions.InvalidStateError'>\n",
            "        <class 'asyncio.exceptions.LimitOverrunError'>\n",
            "        <class 'asyncio.queues.QueueEmpty'>\n",
            "        <class 'asyncio.queues.QueueFull'>\n",
            "        <class 'IPython.core.interactiveshell.SpaceInInput'>\n",
            "        <class 'xml.dom.DOMException'>\n",
            "            <class 'xml.dom.IndexSizeErr'>\n",
            "            <class 'xml.dom.DomstringSizeErr'>\n",
            "            <class 'xml.dom.HierarchyRequestErr'>\n",
            "            <class 'xml.dom.WrongDocumentErr'>\n",
            "            <class 'xml.dom.InvalidCharacterErr'>\n",
            "            <class 'xml.dom.NoDataAllowedErr'>\n",
            "            <class 'xml.dom.NoModificationAllowedErr'>\n",
            "            <class 'xml.dom.NotFoundErr'>\n",
            "            <class 'xml.dom.NotSupportedErr'>\n",
            "            <class 'xml.dom.InuseAttributeErr'>\n",
            "            <class 'xml.dom.InvalidStateErr'>\n",
            "            <class 'xml.dom.SyntaxErr'>\n",
            "            <class 'xml.dom.InvalidModificationErr'>\n",
            "            <class 'xml.dom.NamespaceErr'>\n",
            "            <class 'xml.dom.InvalidAccessErr'>\n",
            "            <class 'xml.dom.ValidationErr'>\n",
            "        <class 'prompt_toolkit.validation.ValidationError'>\n",
            "        <class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
            "        <class 'prompt_toolkit.buffer._Retry'>\n",
            "        <class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
            "        <class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
            "        <class 'email.errors.MessageError'>\n",
            "            <class 'email.errors.MessageParseError'>\n",
            "                <class 'email.errors.HeaderParseError'>\n",
            "                    <class 'email._header_value_parser._InvalidEwError'>\n",
            "                <class 'email.errors.BoundaryError'>\n",
            "            <class 'email.errors.MultipartConversionError'>\n",
            "            <class 'email.errors.CharsetError'>\n",
            "        <class 'uu.Error'>\n",
            "        <class 'http.client.HTTPException'>\n",
            "            <class 'http.client.NotConnected'>\n",
            "            <class 'http.client.InvalidURL'>\n",
            "            <class 'http.client.UnknownProtocol'>\n",
            "            <class 'http.client.UnknownTransferEncoding'>\n",
            "            <class 'http.client.UnimplementedFileMode'>\n",
            "            <class 'http.client.IncompleteRead'>\n",
            "                <class 'urllib3.exceptions.IncompleteRead'>\n",
            "                <class 'urllib3.exceptions.InvalidChunkLength'>\n",
            "            <class 'http.client.ImproperConnectionState'>\n",
            "                <class 'http.client.CannotSendRequest'>\n",
            "                <class 'http.client.CannotSendHeader'>\n",
            "                <class 'http.client.ResponseNotReady'>\n",
            "            <class 'http.client.BadStatusLine'>\n",
            "                <class 'http.client.RemoteDisconnected'>\n",
            "            <class 'http.client.LineTooLong'>\n",
            "        <class 'IPython.core.magics.code.InteractivelyDefined'>\n",
            "        <class 'IPython.terminal.embed.KillEmbedded'>\n",
            "        <class 'ctypes.ArgumentError'>\n",
            "        <class 'zmq.error.ZMQBaseError'>\n",
            "            <class 'zmq.error.ZMQError'>\n",
            "                <class 'zmq.error.ContextTerminated'>\n",
            "                <class 'zmq.error.Again'>\n",
            "                <class 'zmq.error.InterruptedSystemCall'>\n",
            "            <class 'zmq.error.ZMQBindError'>\n",
            "            <class 'zmq.error.NotDone'>\n",
            "        <class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
            "        <class 'configparser.Error'>\n",
            "            <class 'configparser.NoSectionError'>\n",
            "            <class 'configparser.DuplicateSectionError'>\n",
            "            <class 'configparser.DuplicateOptionError'>\n",
            "            <class 'configparser.NoOptionError'>\n",
            "            <class 'configparser.InterpolationError'>\n",
            "                <class 'configparser.InterpolationMissingOptionError'>\n",
            "                <class 'configparser.InterpolationSyntaxError'>\n",
            "                <class 'configparser.InterpolationDepthError'>\n",
            "            <class 'configparser.ParsingError'>\n",
            "                <class 'configparser.MissingSectionHeaderError'>\n",
            "        <class 'jupyter_client.channels.InvalidPortNumber'>\n",
            "        <class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
            "        <class '_curses.error'>\n",
            "        <class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
            "        <class 'tornado.gen.KeyReuseError'>\n",
            "        <class 'tornado.gen.UnknownKeyError'>\n",
            "        <class 'tornado.gen.LeakedCallbackError'>\n",
            "        <class 'tornado.gen.BadYieldError'>\n",
            "        <class 'tornado.gen.ReturnValueIgnoredError'>\n",
            "        <class 'tornado.gen.Return'>\n",
            "        <class 'tornado.queues.QueueEmpty'>\n",
            "        <class 'tornado.queues.QueueFull'>\n",
            "        <class 'distutils.errors.DistutilsError'>\n",
            "            <class 'distutils.errors.DistutilsModuleError'>\n",
            "            <class 'distutils.errors.DistutilsClassError'>\n",
            "            <class 'distutils.errors.DistutilsGetoptError'>\n",
            "            <class 'distutils.errors.DistutilsArgError'>\n",
            "            <class 'distutils.errors.DistutilsFileError'>\n",
            "            <class 'distutils.errors.DistutilsOptionError'>\n",
            "            <class 'distutils.errors.DistutilsSetupError'>\n",
            "            <class 'distutils.errors.DistutilsPlatformError'>\n",
            "            <class 'distutils.errors.DistutilsExecError'>\n",
            "            <class 'distutils.errors.DistutilsInternalError'>\n",
            "            <class 'distutils.errors.DistutilsTemplateError'>\n",
            "            <class 'distutils.errors.DistutilsByteCompileError'>\n",
            "            <class 'setuptools.errors.RemovedCommandError'>\n",
            "            <class 'setuptools.errors.PackageDiscoveryError'>\n",
            "        <class 'distutils.errors.CCompilerError'>\n",
            "            <class 'distutils.errors.PreprocessError'>\n",
            "            <class 'distutils.errors.CompileError'>\n",
            "            <class 'distutils.errors.LibError'>\n",
            "            <class 'distutils.errors.LinkError'>\n",
            "            <class 'distutils.errors.UnknownFileError'>\n",
            "        <class 'zipfile.BadZipFile'>\n",
            "        <class 'zipfile.LargeZipFile'>\n",
            "        <class '_csv.Error'>\n",
            "        <class 'setuptools.extern.packaging._tokenizer.ParserSyntaxError'>\n",
            "        <class 'numpy.linalg.LinAlgError'>\n",
            "        <class 'numpy.lib._iotools.ConverterError'>\n",
            "            <class 'numpy.lib._iotools.ConverterLockError'>\n",
            "        <class 'numpy.ma.core.MAError'>\n",
            "            <class 'numpy.ma.core.MaskError'>\n",
            "        <class 'google.colab.errors.Error'>\n",
            "            <class 'google.colab.errors.AuthorizationError'>\n",
            "            <class 'google.colab.errors.RuntimeManagementError'>\n",
            "            <class 'google.colab._message.MessageError'>\n",
            "        <class 'google.colab.errors.WidgetException'>\n",
            "        <class 'google.colab.output._js_builder.JsException'>\n",
            "        <class 'google.colab._shell_customizations.FormattedTracebackError'>\n",
            "        <class 'psutil.Error'>\n",
            "            <class 'psutil.NoSuchProcess'>\n",
            "                <class 'psutil.ZombieProcess'>\n",
            "            <class 'psutil.AccessDenied'>\n",
            "            <class 'psutil.TimeoutExpired'>\n",
            "        <class 'psutil._pslinux._Ipv6UnsupportedError'>\n",
            "        <class 'pyparsing.exceptions.ParseBaseException'>\n",
            "            <class 'pyparsing.exceptions.ParseException'>\n",
            "            <class 'pyparsing.exceptions.ParseFatalException'>\n",
            "                <class 'pyparsing.exceptions.ParseSyntaxException'>\n",
            "        <class 'pyparsing.exceptions.RecursiveGrammarException'>\n",
            "        <class 'httplib2.error.HttpLib2Error'>\n",
            "            <class 'httplib2.error.HttpLib2ErrorWithResponse'>\n",
            "                <class 'httplib2.error.RedirectMissingLocation'>\n",
            "                <class 'httplib2.error.RedirectLimit'>\n",
            "                <class 'httplib2.error.FailedToDecompressContent'>\n",
            "                <class 'httplib2.error.UnimplementedDigestAuthOptionError'>\n",
            "                <class 'httplib2.error.UnimplementedHmacDigestAuthOptionError'>\n",
            "            <class 'httplib2.error.MalformedHeader'>\n",
            "            <class 'httplib2.error.RelativeURIError'>\n",
            "            <class 'httplib2.error.ServerNotFoundError'>\n",
            "            <class 'httplib2.error.ProxiesUnavailableError'>\n",
            "        <class 'xml.parsers.expat.ExpatError'>\n",
            "        <class 'PIL.Image.DecompressionBombError'>\n",
            "        <class 'cffi.FFIError'>\n",
            "        <class 'cffi.CDefError'>\n",
            "        <class 'cffi.VerificationError'>\n",
            "        <class 'cffi.VerificationMissing'>\n",
            "        <class 'cffi.PkgConfigError'>\n",
            "        <class 'kiwisolver.DuplicateConstraint'>\n",
            "        <class 'kiwisolver.UnsatisfiableConstraint'>\n",
            "        <class 'kiwisolver.UnknownConstraint'>\n",
            "        <class 'kiwisolver.DuplicateEditVariable'>\n",
            "        <class 'kiwisolver.UnknownEditVariable'>\n",
            "        <class 'kiwisolver.BadRequiredStrength'>\n",
            "        <class 'matplotlib.backend_bases.NonGuiException'>\n",
            "        <class 'matplotlib.streamplot.InvalidIndexError'>\n",
            "        <class 'matplotlib.streamplot.TerminateTrajectory'>\n",
            "        <class 'portpicker.NoFreePortFoundError'>\n",
            "        <class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
            "        <class 'xmlrpc.client.Error'>\n",
            "            <class 'xmlrpc.client.ProtocolError'>\n",
            "            <class 'xmlrpc.client.ResponseError'>\n",
            "            <class 'xmlrpc.client.Fault'>\n",
            "        <class 'pkg_resources.extern.packaging._tokenizer.ParserSyntaxError'>\n",
            "        <class 'pkg_resources.ResolutionError'>\n",
            "            <class 'pkg_resources.VersionConflict'>\n",
            "                <class 'pkg_resources.ContextualVersionConflict'>\n",
            "            <class 'pkg_resources.DistributionNotFound'>\n",
            "            <class 'pkg_resources.UnknownExtra'>\n",
            "        <class '_pydevd_bundle.pydevd_runpy._Error'>\n",
            "        <class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
            "        <class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n",
            "        <class 'pyarrow.lib.ArrowException'>\n",
            "            <class 'pyarrow.lib.ArrowInvalid'>\n",
            "            <class 'pyarrow.lib.ArrowMemoryError'>\n",
            "            <class 'pyarrow.lib.ArrowKeyError'>\n",
            "            <class 'pyarrow.lib.ArrowTypeError'>\n",
            "            <class 'pyarrow.lib.ArrowNotImplementedError'>\n",
            "            <class 'pyarrow.lib.ArrowCapacityError'>\n",
            "            <class 'pyarrow.lib.ArrowIndexError'>\n",
            "            <class 'pyarrow.lib.ArrowSerializationError'>\n",
            "                <class 'pyarrow.lib.SerializationCallbackError'>\n",
            "                <class 'pyarrow.lib.DeserializationCallbackError'>\n",
            "            <class 'pyarrow.lib.ArrowCancelled'>\n",
            "        <class 'google.resumable_media.common.InvalidResponse'>\n",
            "        <class 'google.resumable_media.common.DataCorruption'>\n",
            "        <class 'urllib3.exceptions.HTTPError'>\n",
            "            <class 'urllib3.exceptions.PoolError'>\n",
            "                <class 'urllib3.exceptions.RequestError'>\n",
            "                    <class 'urllib3.exceptions.MaxRetryError'>\n",
            "                    <class 'urllib3.exceptions.HostChangedError'>\n",
            "                    <class 'urllib3.exceptions.ReadTimeoutError'>\n",
            "                <class 'urllib3.exceptions.EmptyPoolError'>\n",
            "                <class 'urllib3.exceptions.FullPoolError'>\n",
            "                <class 'urllib3.exceptions.ClosedPoolError'>\n",
            "            <class 'urllib3.exceptions.SSLError'>\n",
            "            <class 'urllib3.exceptions.ProxyError'>\n",
            "            <class 'urllib3.exceptions.DecodeError'>\n",
            "            <class 'urllib3.exceptions.ProtocolError'>\n",
            "                <class 'urllib3.exceptions.ResponseNotChunked'>\n",
            "            <class 'urllib3.exceptions.TimeoutStateError'>\n",
            "            <class 'urllib3.exceptions.TimeoutError'>\n",
            "                <class 'urllib3.exceptions.ReadTimeoutError'>\n",
            "                <class 'urllib3.exceptions.ConnectTimeoutError'>\n",
            "                    <class 'urllib3.exceptions.NewConnectionError'>\n",
            "                        <class 'urllib3.exceptions.NameResolutionError'>\n",
            "            <class 'urllib3.exceptions.NewConnectionError'>\n",
            "                <class 'urllib3.exceptions.NameResolutionError'>\n",
            "            <class 'urllib3.exceptions.LocationValueError'>\n",
            "                <class 'urllib3.exceptions.LocationParseError'>\n",
            "                <class 'urllib3.exceptions.URLSchemeUnknown'>\n",
            "                    <class 'urllib3.exceptions.ProxySchemeUnknown'>\n",
            "            <class 'urllib3.exceptions.ResponseError'>\n",
            "            <class 'urllib3.exceptions.BodyNotHttplibCompatible'>\n",
            "            <class 'urllib3.exceptions.IncompleteRead'>\n",
            "            <class 'urllib3.exceptions.InvalidChunkLength'>\n",
            "            <class 'urllib3.exceptions.InvalidHeader'>\n",
            "            <class 'urllib3.exceptions.HeaderParsingError'>\n",
            "            <class 'urllib3.exceptions.UnrewindableBodyError'>\n",
            "            <class 'requests.exceptions.ContentDecodingError'>\n",
            "        <class 'http.cookies.CookieError'>\n",
            "        <class 'google.protobuf.message.Error'>\n",
            "            <class 'google.protobuf.message.DecodeError'>\n",
            "            <class 'google.protobuf.message.EncodeError'>\n",
            "        <class 'google.protobuf.descriptor.Error'>\n",
            "            <class 'google.protobuf.descriptor.TypeTransformationError'>\n",
            "        <class 'google.protobuf.descriptor_database.Error'>\n",
            "            <class 'google.protobuf.descriptor_database.DescriptorDatabaseConflictingDefinitionError'>\n",
            "        <class 'grpc._cython.cygrpc.AioRpcStatus'>\n",
            "        <class 'grpc._cython.cygrpc.BaseError'>\n",
            "            <class 'grpc._cython.cygrpc.UsageError'>\n",
            "            <class 'grpc._cython.cygrpc.AbortError'>\n",
            "            <class 'grpc._cython.cygrpc.InternalError'>\n",
            "                <class 'grpc._cython.cygrpc.ExecuteBatchError'>\n",
            "            <class 'grpc._cython.cygrpc._ServerStoppedError'>\n",
            "        <class 'grpc._cython.cygrpc._WatchConnectivityFailed'>\n",
            "        <class 'grpc._cython.cygrpc._RequestCallError'>\n",
            "        <class 'grpc.FutureTimeoutError'>\n",
            "        <class 'grpc.FutureCancelledError'>\n",
            "        <class 'grpc.RpcError'>\n",
            "            <class 'grpc.aio._call.AioRpcError'>\n",
            "            <class 'grpc._channel._InactiveRpcError'>\n",
            "            <class 'grpc._channel._Rendezvous'>\n",
            "                <class 'grpc._channel._SingleThreadedRendezvous'>\n",
            "                <class 'grpc._channel._MultiThreadedRendezvous'>\n",
            "        <class 'grpc.experimental.UsageError'>\n",
            "        <class 'google.api_core.exceptions.GoogleAPIError'>\n",
            "            <class 'google.api_core.exceptions.DuplicateCredentialArgs'>\n",
            "            <class 'google.api_core.exceptions.RetryError'>\n",
            "            <class 'google.api_core.exceptions.GoogleAPICallError'>\n",
            "                <class 'google.api_core.exceptions.Redirection'>\n",
            "                    <class 'google.api_core.exceptions.MovedPermanently'>\n",
            "                    <class 'google.api_core.exceptions.NotModified'>\n",
            "                    <class 'google.api_core.exceptions.TemporaryRedirect'>\n",
            "                    <class 'google.api_core.exceptions.ResumeIncomplete'>\n",
            "                <class 'google.api_core.exceptions.ClientError'>\n",
            "                    <class 'google.api_core.exceptions.BadRequest'>\n",
            "                        <class 'google.api_core.exceptions.InvalidArgument'>\n",
            "                        <class 'google.api_core.exceptions.FailedPrecondition'>\n",
            "                        <class 'google.api_core.exceptions.OutOfRange'>\n",
            "                    <class 'google.api_core.exceptions.Unauthorized'>\n",
            "                        <class 'google.api_core.exceptions.Unauthenticated'>\n",
            "                    <class 'google.api_core.exceptions.Forbidden'>\n",
            "                        <class 'google.api_core.exceptions.PermissionDenied'>\n",
            "                    <class 'google.api_core.exceptions.NotFound'>\n",
            "                    <class 'google.api_core.exceptions.MethodNotAllowed'>\n",
            "                    <class 'google.api_core.exceptions.Conflict'>\n",
            "                        <class 'google.api_core.exceptions.AlreadyExists'>\n",
            "                        <class 'google.api_core.exceptions.Aborted'>\n",
            "                    <class 'google.api_core.exceptions.LengthRequired'>\n",
            "                    <class 'google.api_core.exceptions.PreconditionFailed'>\n",
            "                    <class 'google.api_core.exceptions.RequestRangeNotSatisfiable'>\n",
            "                    <class 'google.api_core.exceptions.TooManyRequests'>\n",
            "                        <class 'google.api_core.exceptions.ResourceExhausted'>\n",
            "                    <class 'google.api_core.exceptions.Cancelled'>\n",
            "                <class 'google.api_core.exceptions.ServerError'>\n",
            "                    <class 'google.api_core.exceptions.InternalServerError'>\n",
            "                    <class 'google.api_core.exceptions.Unknown'>\n",
            "                    <class 'google.api_core.exceptions.DataLoss'>\n",
            "                    <class 'google.api_core.exceptions.MethodNotImplemented'>\n",
            "                    <class 'google.api_core.exceptions.BadGateway'>\n",
            "                    <class 'google.api_core.exceptions.ServiceUnavailable'>\n",
            "                    <class 'google.api_core.exceptions.GatewayTimeout'>\n",
            "                        <class 'google.api_core.exceptions.DeadlineExceeded'>\n",
            "        <class 'google.api_core.iam.InvalidOperationException'>\n",
            "        <class 'google.auth.exceptions.GoogleAuthError'>\n",
            "            <class 'google.auth.exceptions.TransportError'>\n",
            "            <class 'google.auth.exceptions.RefreshError'>\n",
            "                <class 'google.auth.exceptions.ReauthFailError'>\n",
            "                    <class 'google.auth.exceptions.ReauthSamlChallengeFailError'>\n",
            "            <class 'google.auth.exceptions.UserAccessTokenError'>\n",
            "            <class 'google.auth.exceptions.DefaultCredentialsError'>\n",
            "                <class 'google.auth.exceptions.MalformedError'>\n",
            "                <class 'google.auth.exceptions.InvalidResource'>\n",
            "                <class 'google.auth.exceptions.InvalidOperation'>\n",
            "                <class 'google.auth.exceptions.InvalidValue'>\n",
            "                <class 'google.auth.exceptions.InvalidType'>\n",
            "                <class 'google.auth.exceptions.OSError'>\n",
            "            <class 'google.auth.exceptions.MutualTLSChannelError'>\n",
            "            <class 'google.auth.exceptions.ClientCertError'>\n",
            "            <class 'google.auth.exceptions.OAuthError'>\n",
            "        <class 'ffi.error'>\n",
            "        <class 'cryptography.exceptions.UnsupportedAlgorithm'>\n",
            "        <class 'cryptography.exceptions.AlreadyFinalized'>\n",
            "        <class 'cryptography.exceptions.AlreadyUpdated'>\n",
            "        <class 'cryptography.exceptions.NotYetFinalized'>\n",
            "        <class 'cryptography.exceptions.InvalidTag'>\n",
            "        <class 'cryptography.exceptions.InvalidSignature'>\n",
            "        <class 'cryptography.exceptions.InternalError'>\n",
            "        <class 'cryptography.exceptions.InvalidKey'>\n",
            "        <class 'cryptography.utils.InterfaceNotImplemented'>\n",
            "        <class 'cryptography.x509.general_name.UnsupportedGeneralNameType'>\n",
            "        <class 'cryptography.x509.extensions.DuplicateExtension'>\n",
            "        <class 'cryptography.x509.extensions.ExtensionNotFound'>\n",
            "        <class 'cryptography.x509.base.AttributeNotFound'>\n",
            "        <class 'cryptography.x509.base.InvalidVersion'>\n",
            "        <class 'pytz.exceptions.Error'>\n",
            "            <class 'pytz.exceptions.UnknownTimeZoneError'>\n",
            "            <class 'pytz.exceptions.InvalidTimeError'>\n",
            "                <class 'pytz.exceptions.AmbiguousTimeError'>\n",
            "                <class 'pytz.exceptions.NonExistentTimeError'>\n",
            "        <class 'pandas.errors.NumbaUtilError'>\n",
            "        <class 'pandas.errors.InvalidIndexError'>\n",
            "        <class 'pandas.errors.DataError'>\n",
            "        <class 'pandas.errors.SpecificationError'>\n",
            "        <class 'pandas.errors.IndexingError'>\n",
            "        <class 'pandas.errors.PossibleDataLossError'>\n",
            "        <class 'pandas.errors.ClosedFileError'>\n",
            "        <class 'pandas.core.dtypes.cast.LossySetitemError'>\n",
            "        <class 'pyarrow.vendored.docscrape.ParseError'>\n",
            "        <class 'pandas.core.arrays.datetimelike.InvalidComparison'>\n",
            "        <class 'tarfile.TarError'>\n",
            "            <class 'tarfile.ExtractError'>\n",
            "            <class 'tarfile.ReadError'>\n",
            "            <class 'tarfile.CompressionError'>\n",
            "            <class 'tarfile.StreamError'>\n",
            "            <class 'tarfile.HeaderError'>\n",
            "                <class 'tarfile.EmptyHeaderError'>\n",
            "                <class 'tarfile.TruncatedHeaderError'>\n",
            "                <class 'tarfile.EOFHeaderError'>\n",
            "                <class 'tarfile.InvalidHeaderError'>\n",
            "                <class 'tarfile.SubsequentHeaderError'>\n",
            "            <class 'tarfile.FilterError'>\n",
            "                <class 'tarfile.AbsolutePathError'>\n",
            "                <class 'tarfile.OutsideDestinationError'>\n",
            "                <class 'tarfile.SpecialFileError'>\n",
            "                <class 'tarfile.AbsoluteLinkError'>\n",
            "                <class 'tarfile.LinkOutsideDestinationError'>\n",
            "        <class 'pandas.core.interchange.utils.NoBufferPresent'>\n",
            "        <class 'google.protobuf.json_format.Error'>\n",
            "            <class 'google.protobuf.json_format.SerializeToJsonError'>\n",
            "            <class 'google.protobuf.json_format.ParseError'>\n",
            "        <class 'google.api_core.future.polling._OperationNotComplete'>\n",
            "        <class 'google.cloud.bigquery.exceptions.BigQueryError'>\n",
            "            <class 'google.cloud.bigquery.exceptions.LegacyBigQueryStorageError'>\n",
            "            <class 'google.cloud.bigquery.exceptions.LegacyPyarrowError'>\n",
            "        <class 'shapely.errors.ShapelyError'>\n",
            "            <class 'shapely.errors.GEOSException'>\n",
            "            <class 'shapely.errors.UnsupportedGEOSVersionError'>\n",
            "            <class 'shapely.errors.DimensionError'>\n",
            "            <class 'shapely.errors.TopologicalError'>\n",
            "            <class 'shapely.errors.EmptyPartError'>\n",
            "            <class 'shapely.errors.GeometryTypeError'>\n",
            "        <class 'google.cloud.bigquery.dbapi.exceptions.Warning'>\n",
            "        <class 'google.cloud.bigquery.dbapi.exceptions.Error'>\n",
            "            <class 'google.cloud.bigquery.dbapi.exceptions.InterfaceError'>\n",
            "            <class 'google.cloud.bigquery.dbapi.exceptions.DatabaseError'>\n",
            "                <class 'google.cloud.bigquery.dbapi.exceptions.DataError'>\n",
            "                <class 'google.cloud.bigquery.dbapi.exceptions.OperationalError'>\n",
            "                <class 'google.cloud.bigquery.dbapi.exceptions.IntegrityError'>\n",
            "                <class 'google.cloud.bigquery.dbapi.exceptions.InternalError'>\n",
            "                <class 'google.cloud.bigquery.dbapi.exceptions.ProgrammingError'>\n",
            "                <class 'google.cloud.bigquery.dbapi.exceptions.NotSupportedError'>\n",
            "        <class 'google.cloud.bigquery.magics.line_arg_parser.exceptions.ParseError'>\n",
            "            <class 'google.cloud.bigquery.magics.line_arg_parser.exceptions.QueryParamsParseError'>\n",
            "            <class 'google.cloud.bigquery.magics.line_arg_parser.exceptions.DuplicateQueryParamsError'>\n",
            "    <class 'GeneratorExit'>\n",
            "    <class 'SystemExit'>\n",
            "    <class 'KeyboardInterrupt'>\n",
            "    <class 'asyncio.exceptions.CancelledError'>\n",
            "    <class 'setuptools._vendor.more_itertools.more.AbortThread'>\n",
            "    <class 'pkg_resources._vendor.more_itertools.more.AbortThread'>\n",
            "    <class 'pyo3_runtime.PanicException'>\n"
          ]
        }
      ],
      "source": [
        "def print_hierarchy(exception_class, indent=0):\n",
        "    print(' ' * indent + str(exception_class))\n",
        "    for subclass in exception_class.__subclasses__():\n",
        "        print_hierarchy(subclass, indent + 4)\n",
        "\n",
        "print_hierarchy(BaseException)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
      ],
      "metadata": {
        "id": "yN7-jfuLuyrv"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "The arithmeticerror class is a base class for exceptions that occur during arithmetic operations in Python. it is a parent class for various arithmetic-related exception classes. Two commonly used exceptions derived from the ArithmeticError class are ZeroDivisionError and OverflowError\n",
        "\n",
        "\n",
        "ZeroDivisionError:\n",
        "this exception is raised when attempting to divide a number by zero. Division by zero is mathematically undefined, and therefore, Python raises this error to prevent such operations.\n",
        "\n",
        "OverflowError:\n",
        "this exception is raised when the result of an arithmetic operation exceeds the limits of the data type being used. For example, attempting to store a value larger than the maximum representable value for a data type will result in a overflow error."
      ],
      "metadata": {
        "id": "VCau-DH6ugeA"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "a = 10\n",
        "b = 0\n",
        "\n",
        "try:\n",
        "    result = a / b\n",
        "except ZeroDivisionError as e:\n",
        "    print(\"Error:\", e)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Z6Kz7zS2vSA4",
        "outputId": "08ba300f-4709-4e5f-8aab-523f7d73f125"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: division by zero\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import math\n",
        "\n",
        "try:\n",
        "    factorial = math.exp(10000)\n",
        "except OverflowError as e:\n",
        "    print(\"Error:\", e)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "egX11ep3wlZf",
        "outputId": "c3a69a4c-01a9-4a49-9aca-ccb454abd34a"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: math range error\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
        "\n",
        "the lookuprrror class in Python is a base clss for exceptions that occur when a lookup or indexing operation is unsuccessful due to a missing or invalid key or index. It is a parent class for lookup-related exceptions like keyerror and indexerror. this hierarchy of exception classes allows you to handle different types of lookup errors more precisely.\n",
        "\n",
        "\n",
        "keyerror- when we enter a key value that is not present in the dict it will raise key error."
      ],
      "metadata": {
        "id": "ecz8UGKpxP9B"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#KeyError: is raised when you try to access a dictionary key that doesn't exist.\n",
        "my_dict = {\"a\": 1, \"b\": 2, \"c\": 3}\n",
        "\n",
        "try:\n",
        "    value = my_dict[\"d\"]\n",
        "except KeyError as e:\n",
        "    print(\"Error:\", e)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dmwFg4Q4w-Of",
        "outputId": "bd58acff-3098-4801-a97a-c2e8e239bae5"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: 'd'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**index error- index error hapens when we try to access an index in a list or data frame that dosen't exist.**\n"
      ],
      "metadata": {
        "id": "Q7oug82hBtsF"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "my_list = [10, 20, 30]\n",
        "\n",
        "try:\n",
        "    value = my_list[5]  # Attempting to access an index that doesn't exist\n",
        "except IndexError as e:\n",
        "    print(\"Error:\", e)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yDbZX44NxllY",
        "outputId": "5cb276fd-8433-4de4-b66d-97003488f6f0"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: list index out of range\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q5. Explain ImportError. What is ModuleNotFoundError?"
      ],
      "metadata": {
        "id": "p1S2UVU0CB-F"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "ImportError and ModuleNotFoundError are both exceptions in Python that occur when there are issues related to importing and using modules in your code.\n",
        "\n",
        "**import error is a base exception that occurs when we try to import a module that dosen't exist or when imported module is not loaded properly. there are many reasons that can raise this type of error.**\n",
        "the module you are trying to export dosen't exist\n",
        "\n",
        "spelling of the module is wrong\n",
        "\n",
        "runtime errors etc.\n",
        "\n",
        "on the other hand module not found error is also a part of import error but this error raises specific type of error.\n",
        " it is raised when a module cannot be found during the import process.in other words, it is a specialized version of ImportError that indicates that the requested module could not be located."
      ],
      "metadata": {
        "id": "22KGe6ODCkHN"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "try:\n",
        "    import module_that_does_not_exist\n",
        "except ImportError as e:\n",
        "    print(\"Module not found or cannot be imported.\",e)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Bbf5b7mrECGG",
        "outputId": "9fabd63d-63db-4d1b-f65b-640d929f18af"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Module not found or cannot be imported. No module named 'module_that_does_not_exist'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q6. List down some best practices for exception handling in python."
      ],
      "metadata": {
        "id": "TcnzOqptFdD_"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "catch only the exceptions that you are expecting,\n",
        "avoid using bare except statements because they can catch unexpected errors.\n",
        "\n",
        "Use specific exception classes or multiple except blocks to handle different types of exceptions separately.\n",
        "\n",
        "write only necessary code inside the try block, try to keep  it as small as possible.\n",
        "\n",
        "Pprovide clear and descriptive error Message.\n",
        "\n",
        "Use the finally block to ensure cleanup the code and to tasks like closing files, releasing resources etc.\n",
        "\n",
        "create custom exception classes when needed to raise specific error conditions in your code.\n",
        "\n",
        "inherit from the base Exception class\n",
        "\n",
        "use the Python logging module to log exceptions."
      ],
      "metadata": {
        "id": "Cipx0wYtF0L9"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "lenrGb6IEmaO"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}